// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace CustomizationsInCadl.Models
{
    [CodeGenMemberSerializationHooks(nameof(StringToBeChanged), SerializationValueHook = null, DeserializationValueHook = null)] // we use this attribute here to change the serialization of this property back to its default
    public partial class ThirdLayer : SecondLayer
    {
    }
}
