resources:
- repo: self
steps:
- task: CmdLine@1
  inputs:
    filename: cmd
    arguments: '/c "node -v & npm -v & python --version & ruby --version & go version & javac -version"'

- task: CmdLine@1
  inputs:
    filename: npm
    arguments: install

- task: CmdLine@1
  inputs:
    filename: npm
    arguments: 'run testci'

- task: CmdLine@1
  inputs:
    filename: npm
    arguments: 'run show-results -- $(Build.Repository.Name) $(Build.SourceBranch) $(github-token) $(storage-coverage-user) $(storage-coverage-pass)'
    workingFolder: 'node_modules/@microsoft.azure/autorest.testserver'
  continueOnError: true

