// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for
// license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Fixtures.MirrorSequences.Models
{
    using Microsoft.Rest;
    using System.Collections;

    /// <summary>
    /// Exception thrown for an invalid response with ErrorModelListException
    /// information.
    /// </summary>
    public partial class ErrorModelException : HttpRestExceptionBase<IList<ErrorModelListException>>
    {

        /// <summary>
        /// Initializes a new instance of the ErrorModelException class.
        /// </summary>
        public ErrorModelException()
        {
        }

        /// <summary>
        /// Initializes a new instance of the ErrorModelException class.
        /// </summary>
        /// <param name="message">The exception message.</param>
        public ErrorModelException(string message)
            : this(message, null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the ErrorModelException class.
        /// </summary>
        /// <param name="message">The exception message.</param>
        /// <param name="innerException">Inner exception.</param>
        public ErrorModelException(string message, System.Exception innerException)
            : base(message, innerException)
        {
        }

        /// <summary>
        /// Returns list of deserialized error models
        /// </summary>
        public System.Collections.IList<ErrorModelListException> ErrorModels => Body;
    }
}
