alias IMAGE_SIZES = "256x256" | "512x512" | "1024x1024";

alias CHAT_COMPLETION_MODELS =
  | "gpt4"
  | "gpt-4-0314"
  | "gpt-4-0613"
  | "gpt-4-32k"
  | "gpt-4-32k-0314"
  | "gpt-4-32k-0613"
  | "gpt-3.5-turbo"
  | "gpt-3.5-turbo-16k"
  | "gpt-3.5-turbo-0301"
  | "gpt-3.5-turbo-0613"
  | "gpt-3.5-turbo-16k-0613";

alias COMPLETION_MODELS =
  | "babbage-002"
  | "davinci-002"
  | "text-davinci-003"
  | "text-davinci-002"
  | "text-davinci-001"
  | "code-davinci-002"
  | "text-curie-001"
  | "text-babbage-001"
  | "text-ada-001";
