// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace Fixtures.Azure.Fluent.AcceptanceTestsAzureResource
{
    using Microsoft.Rest;
    using Microsoft.Rest.Azure;
    using Models;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Resource Flattening for AutoRest
    /// </summary>
    public partial interface IAutoRestResourceFlatteningTestService : System.IDisposable
    {
        /// <summary>
        /// Gets or sets the base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets JSON serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets JSON deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }

        /// <summary>
        /// Credentials needed for the client to connect to Azure.
        /// </summary>
        ServiceClientCredentials Credentials { get; }

        /// <summary>
        /// Gets or sets the preferred language for the response.
        /// </summary>
        string AcceptLanguage { get; set; }

        /// <summary>
        /// Gets or sets the retry timeout in seconds for Long Running Operations. Default value is 30.
        /// </summary>
        int? LongRunningOperationRetryTimeout { get; set; }

        /// <summary>
        /// When set to true a unique x-ms-client-request-id value is generated and included in each request. Default is true.
        /// </summary>
        bool? GenerateClientRequestId { get; set; }


        /// <summary>
        /// Put External Resource as an Array
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceArray'>
        /// External Resource as an Array to put
        /// </param>
        void PutArray(IList<ResourceInner> resourceArray = default(IList<ResourceInner>));

        /// <summary>
        /// Put External Resource as an Array
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceArray'>
        /// External Resource as an Array to put
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task PutArrayAsync(IList<ResourceInner> resourceArray = default(IList<ResourceInner>), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get External Resource as an Array
        /// <see href='http://tempuri.org' />
        /// </summary>
        IList<FlattenedProductInner> GetArray();

        /// <summary>
        /// Get External Resource as an Array
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IList<FlattenedProductInner>> GetArrayAsync(CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Put External Resource as a Dictionary
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceDictionary'>
        /// External Resource as a Dictionary to put
        /// </param>
        void PutDictionary(IDictionary<string, FlattenedProductInner> resourceDictionary = default(IDictionary<string, FlattenedProductInner>));

        /// <summary>
        /// Put External Resource as a Dictionary
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceDictionary'>
        /// External Resource as a Dictionary to put
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task PutDictionaryAsync(IDictionary<string, FlattenedProductInner> resourceDictionary = default(IDictionary<string, FlattenedProductInner>), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get External Resource as a Dictionary
        /// <see href='http://tempuri.org' />
        /// </summary>
        IDictionary<string, FlattenedProductInner> GetDictionary();

        /// <summary>
        /// Get External Resource as a Dictionary
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<IDictionary<string, FlattenedProductInner>> GetDictionaryAsync(CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Put External Resource as a ResourceCollection
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceComplexObject'>
        /// External Resource as a ResourceCollection to put
        /// </param>
        void PutResourceCollection(ResourceCollectionInner resourceComplexObject = default(ResourceCollectionInner));

        /// <summary>
        /// Put External Resource as a ResourceCollection
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='resourceComplexObject'>
        /// External Resource as a ResourceCollection to put
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task PutResourceCollectionAsync(ResourceCollectionInner resourceComplexObject = default(ResourceCollectionInner), CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Get External Resource as a ResourceCollection
        /// <see href='http://tempuri.org' />
        /// </summary>
        ResourceCollectionInner GetResourceCollection();

        /// <summary>
        /// Get External Resource as a ResourceCollection
        /// <see href='http://tempuri.org' />
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<ResourceCollectionInner> GetResourceCollectionAsync(CancellationToken cancellationToken = default(CancellationToken));
    }
}
