// <auto-generated>
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

namespace Fixtures.Azure.Fluent.AcceptanceTestsAzureSpecials
{
    using Microsoft.Rest;
    using Microsoft.Rest.Azure;
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// ApiVersionDefaultOperations operations.
    /// </summary>
    public partial interface IApiVersionDefaultOperations
    {
        IApiVersionDefaultOperationsWithHttpMessages WithHttpMessages();

        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        void GetMethodGlobalValid();

        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task GetMethodGlobalValidAsync(CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        void GetMethodGlobalNotProvidedValid();

        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task GetMethodGlobalNotProvidedValidAsync(CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        void GetPathGlobalValid();

        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task GetPathGlobalValidAsync(CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        void GetSwaggerGlobalValid();

        /// <summary>
        /// GET method with api-version modeled in global settings.
        /// </summary>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task GetSwaggerGlobalValidAsync(CancellationToken cancellationToken = default(CancellationToken));
    }
}
