pr:
  branches:
    include:
    - feature/*

variables:
  nugetMultiFeedWarnLevel: 'none'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20230428.1

env:
  GH_TOKEN: $(azuresdk-github-pat)

jobs:
  - job: "Regen_and_Push"
    timeoutInMinutes: 30
    pool:
      name: azsdk-pool-mms-win-2022-general
      vmImage: windows-2022
    steps:
      - checkout: self
        fetchDepth: 1
      - checkout: azure-sdk-tools
        fetchDepth: 1      
      - script: |
          gh pr checkout $(System.PullRequest.PullRequestNumber)
        displayName: 'Check out PR branch'
        workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
      - task: UseDotNet@2
        displayName: 'Use .NET Core SDK'
        retryCountOnTaskFailure: 3
        inputs:
          useGlobalJson: true
          performMultiLevelLookup: true
      - task: NodeTool@0
        displayName: "Install Node 18.x"
        inputs:
          versionSpec: '18.x'
      - script: |
          npm ci
        displayName: "Install packages"
        workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
      - pwsh: ./eng/Generate.ps1
        displayName: "Generate Codes"
        workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
      - pwsh: ./eng/ParsePRInfo.ps1 -SourceBranch $(System.PullRequest.SourceBranch)
        name: PRUrl
        displayName: "Build PR Url"
        workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
      # - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
      #   parameters:
      #     BaseRepoBranch: auto-update-autorest-${{ parameters.AutorestCSharpVersion }}
      #     BaseRepoOwner: azure-sdk
      #     CommitMsg: Update SDK codes ${{ parameters.filter }}
      #     TargetRepoOwner: Azure
      #     TargetRepoName: feature/v3
      #     WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      #     ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts