trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

jobs:
  - job: Build
    variables:
      DotNetCoreSDKVersion: 3.0.100
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          version: "$(DotNetCoreSDKVersion)"
      - script: |
          dotnet test AutoRest.CSharp.V3.sln -warnaserror
        displayName: "Build"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - script: |
          npm install -g @autorest/autorest
        displayName: "Install autorest-beta"
      - script: |
          autorest-beta --debug --verbose --use:$(Build.SourcesDirectory) --input-file:$(Build.SourcesDirectory)\samples\xkcd\xkcd.yaml
        displayName: "Run autorest on xkcd"