trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

variables:
  BlobFeedUrl: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
  OfficialBuildId: $(Build.BuildNumber)

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools

stages:
  - stage: 'Build_and_Test'
    jobs:
      - job: Build
        timeoutInMinutes: 120
        pool:
          vmImage: windows-2019
        steps:
          - checkout: self
          - checkout: azure-sdk-tools
          - task: NodeTool@0
            displayName: "Install Node 14.x"
            inputs:
              versionSpec: '14.x'
          - script: |
              npm ci
            displayName: "Install packages"
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp   
          - script: 'dotnet pack src/AutoRest.CSharp/AutoRest.CSharp.csproj -o $(Build.ArtifactStagingDirectory) -warnaserror'
            name: Package
            displayName: 'Package'
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0
          - pwsh: ./eng/CodeChecks.ps1
            displayName: "Check if code is up-to-date"
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
          - script: |
              dotnet test AutoRest.CSharp.sln
            displayName: "Test"
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
          - script: |
              dotnet test AutoRest.CSharp.sln -c Release
            displayName: "Test Release Configuration"
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
          - task: PublishBuildArtifacts@1
            condition: succeededOrFailed()
            displayName: 'Publish Artifacts'
            inputs:
              ArtifactName: packages
          - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
            - pwsh: > 
                ./eng/PublishRelease.ps1
                -WorkingDirectory ./artifacts/bin/AutoRest.CSharp/Debug/netcoreapp3.0/
                -GitHubToken $(azuresdk-github-pat)
                -NpmToken $(azure-sdk-npm-token)
                -BuildNumber $(Build.BuildNumber)
                -Sha $(Build.SourceVersion)
                -CoverageUser $(storage-coverage-user)
                -CoveragePass $(storage-coverage-pass)
              failOnStderr: false
              displayName: 'Publish to GitHub, npm and coverage report'
              workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
      - template: smoke-test.yml
        parameters:
          name: SmokeTest_A_C
          filter: "^[a-b]"
      - template: smoke-test.yml
        parameters:
          name: SmokeTest_C_I
          filter: "^[c-i]"
      - template: smoke-test.yml
        parameters:
          name: SmokeTest_J_R
          filter: "^[j-r]"
      - template: smoke-test.yml
        parameters:
          name: SmokeTest_S_Z
          filter: "^[s-z]"
  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
    - template: pipelines/stages/net-release-blobfeed.yml@azure-sdk-build-tools  
      parameters:
        ShouldTag: false
        ShouldSign: false
        ShouldPublishSymbols: false
    - stage: 'Update_azure_sdk_for_net'
      dependsOn: 
        - Build_and_Test
        - Release
      jobs:
        - job: Update
          pool:
            vmImage: ubuntu-20.04
          variables:
            AutorestCSharpVersion: $[stageDependencies.Build_and_Test.Build.outputs['Package.AutorestCSharpVersion']]
          steps:
            - checkout: self
            - checkout: azure-sdk-for-net
            - checkout: azure-sdk-tools
            - pwsh: ./eng/UpdateAzureSdkForNet.ps1 -Version $(AutorestCSharpVersion) -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
              failOnStderr: false
              workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
              displayName: 'Update generator version in Azure SDK repo'
            - template: /eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
              parameters:
                BaseBranchName: master
                RepoName: azure-sdk-for-net
                PRBranchName: auto-update-autorest
                CommitMsg: Update AutoRest C# version to $(AutorestCSharpVersion)
                PRBody: Update AutoRest C# version to $(AutorestCSharpVersion)
                PRTitle:  Update AutoRest C# version
                PushArgs: -f
                WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
                ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
