trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

jobs:
  - job: Build
    variables:
      DotNetCoreSDKVersion: 3.0.100
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          version: "$(DotNetCoreSDKVersion)"
      - script: |
          npm install
        displayName: "Install packages"
      - script: |
          dotnet build AutoRest.CSharp.V3.sln
        displayName: "Build"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - task: PowerShell@2
        displayName: "Verify generated code"
        inputs:
          filePath: "eng/CodeChecks.ps1"
          failOnStderr:  false
      - script: |
          dotnet test AutoRest.CSharp.V3.sln
        displayName: "Test"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0