trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

variables:
  BlobFeedUrl: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
  OfficialBuildId: $(Build.BuildNumber)
  NugetSecurityAnalysisWarningLevel: 'none'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20230428.1
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
      ref: main
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
      ref: refs/tags/azure-sdk-build-tools_20230307.1

stages:
  - stage: 'Build_and_Test'
    jobs:
      - template: build-and-test.yml
        parameters:
        IsTspDevVersionTest: true
      - template: check-code-generation.yml
        parameters:
          name: Check_Code_Generation_A_C
          filter: "^[a-b]"
      - template: check-code-generation.yml
        parameters:
          name: Check_Code_Generation_C_I
          filter: "^[c-i]"
      - template: check-code-generation.yml
        parameters:
          name: Check_Code_Generation_J_R
          filter: "^[j-r]"
      - template: check-code-generation.yml
        parameters:
          name: Check_Code_Generation_S_Z
          filter: "^[s-z]"
  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:
    - template: pipelines/stages/net-release-to-feed.yml@azure-sdk-build-tools
      parameters:
        ShouldTag: false
        ShouldSign: false
        ShouldPublishSymbols: false
    - stage: 'Update_azure_sdk_for_net'
      dependsOn:
        - Build_and_Test
        - Release
      variables:
        AutorestCSharpVersion: $[stageDependencies.Build_and_Test.Build.outputs['Package.AutorestCSharpVersion']]
        CadlEmitterVersion: $[stageDependencies.Build_and_Test.Build.outputs['Publish.CadlEmitterVersion']]
      jobs:
        - template: update-generator-versions.yml
          parameters:
            AutorestCSharpVersion: $(AutorestCSharpVersion)
            CadlEmitterVersion: $(CadlEmitterVersion)
# update codes
        - template: generate-sdk-job-matrix-files.yml
          parameters:
            Name: Generate_Job_Matrix
            JobCount: 7
        - template: update-azure-sdk-for-net-codes.yml
          parameters:
            Name: Update_Code
            Matrix: $[dependencies.Generate_Job_Matrix.outputs['generate_job_matrix.matrix']]
            AutorestCSharpVersion: $(AutorestCSharpVersion)
            CadlEmitterVersion: $(CadlEmitterVersion)
            DependsOn: Generate_Job_Matrix
# update samples
        - template: update-azure-sdk-for-net-samples.yml
          parameters:
            name: Update_Samples_A_F
            filter: "a*,b*,c*,d*,e*,f*"
        - template: update-azure-sdk-for-net-samples.yml
          parameters:
            name: Update_Samples_G_L
            filter: "g*,h*,i*,j*,k*,l*"
        - template: update-azure-sdk-for-net-samples.yml
          parameters:
            name: Update_Samples_M_R
            filter: "m*,n*,o*,p*,q*,r*"
        - template: update-azure-sdk-for-net-samples.yml
          parameters:
            name: Update_Samples_S_Z
            filter: "s*,t*,u*,v*,w*,x*,y*,z*"
        - job: Create_PR
          dependsOn:
            - Update_Code
            - Update_Samples_A_F
            - Update_Samples_G_L
            - Update_Samples_M_R
            - Update_Samples_S_Z
          steps:
            - checkout: self
            - checkout: azure-sdk-tools
            - task: PowerShell@2
              displayName: Create pull request
              inputs:
                pwsh: true
                filePath: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts/Submit-PullRequest.ps1
                arguments: >
                  -RepoOwner "Azure"
                  -RepoName "azure-sdk-for-net"
                  -BaseBranch "main"
                  -PROwner "azure-sdk"
                  -PRBranch "auto-update-autorest-$(AutorestCSharpVersion)"
                  -AuthToken "$(azuresdk-github-pat)"
                  -PRTitle "Update AutoRest C# version to $(AutorestCSharpVersion)"
                  -PRBody "Update AutoRest C# version to $(AutorestCSharpVersion)"
