trigger:
  branches:
    include:
    - feature/*

pr:
  branches:
    include:
    - feature/*

jobs:
  - job: Build
    variables:
      DotNetCoreSDKVersion: 3.0.100
    pool:
      vmImage: windows-2019
    steps:
      - task: DotNetCoreInstaller@2
        displayName: "Use .NET Core sdk $(DotNetCoreSDKVersion)"
        inputs:
          version: "$(DotNetCoreSDKVersion)"
      - script: |
          npm install
        displayName: "Install packages"
      - script: |
          dotnet build AutoRest.CSharp.V3.sln
        displayName: "Build"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - pwsh: ./eng/CodeChecks.ps1
        displayName: "Check if code is up-to-date"
      - script: |
          dotnet test AutoRest.CSharp.V3.sln
        displayName: "Test"
        env:
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_MULTILEVEL_LOOKUP: 0
      - script: |
          dotnet msbuild /t:NpmPackage src/AutoRest.CSharp.V3/AutoRest.CSharp.V3.csproj
      - task: PublishBuildArtifacts@1
        inputs:
          contents: artifacts/bin/AutoRest.CSharp.V3/Debug/netcoreapp3.0/*.tgz
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          