parameters:
  name: ''
  filter: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    name: azsdk-pool-mms-win-2019-general
    vmImage: MMS2019
  steps:
    - task: NodeTool@0
      displayName: "Install Node 18.13.0"
      inputs:
        versionSpec: '18.13.0'
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        useGlobalJson: true
        performMultiLevelLookup: true
    - script: |
        npm ci
      displayName: "Install packages"
    - pwsh: .\eng\GeneratedCodeCheck.ps1 -Filter "${{ parameters.filter }}"
      displayName: "Check if generated codes are up-to-date"
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_MULTILEVEL_LOOKUP: 0
