# Generate projects of smoke tests, projects under `samples` and `test` folders.
# Also check if projects under `samples` and `test` folders are updated.

parameters:
  name: ''
  filter: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    name: azsdk-pool-mms-ubuntu-2204-general
    vmImage: ubuntu-22.04
  steps:
    - task: NodeTool@0
      displayName: "Install Node 18.13.0"
      inputs:
        versionSpec: '18.13.0'
    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        useGlobalJson: true
        performMultiLevelLookup: true
    - script: |
        npm ci
      displayName: "Install packages"
    - pwsh: .\eng\CodeGenerationCheck.ps1 -Filter "${{ parameters.filter }}"
      displayName: "Check if generated code is up-to-date"
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_MULTILEVEL_LOOKUP: 0
