trigger:
  branches:
    include:
    - feature/*
    - pipelinetest

pr:
  branches:
    include:
    - feature/*
    - pipelinetest

variables:
  BlobFeedUrl: https://azuresdkartifacts.blob.core.windows.net/azure-sdk-tools/index.json
  OfficialBuildId: $(Build.BuildNumber)
  NugetSecurityAnalysisWarningLevel: 'none'

resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
    - repository: azure-sdk-build-tools
      type: git
      name: internal/azure-sdk-build-tools
      ref: refs/tags/azure-sdk-build-tools_20211215.1

stages:
  - stage: 'Build_and_Test'
    jobs:
      - job: MockInit
        timeoutInMinutes: 180
        pool:
          name: azsdk-pool-mms-win-2019-general
          vmImage: MMS2019
        steps:
          - checkout: self
          - checkout: azure-sdk-tools
          - task: UseDotNet@2
            displayName: 'Use .NET Core SDK'
            retryCountOnTaskFailure: 3
            inputs:
              useGlobalJson: true
              performMultiLevelLookup: true
          - task: NodeTool@0
            displayName: "Install Node 16.x"
            inputs:
              versionSpec: '16.6.2'
          - script: |
              npm ci
            displayName: "Install packages"
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
          - script: 'dotnet pack src/AutoRest.CSharp/AutoRest.CSharp.csproj -o $(Build.ArtifactStagingDirectory) -warnaserror -c Release'
            name: Package
            displayName: 'Package'
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
            env:
              DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
              DOTNET_CLI_TELEMETRY_OPTOUT: 1
              DOTNET_MULTILEVEL_LOOKUP: 0
          - script: |
              pwsh ./eng/GenerateAndExecuteMockTest.ps1
            displayName: "GenerateAndExecuteMockTest"
            workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        parameters:
          name: SmokeTest_S_Z
          filter: "^[s-z]"
