trigger: none

resources:
  repositories:
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20220404.3

stages:
  - stage: 'Build_And_Generate'
    jobs:
    - job: Build_And_Generate
      timeoutInMinutes: 120
      pool:
        name: azsdk-pool-mms-win-2022-general
        vmImage: windows-2022
      steps:
        - checkout: self
        - checkout: azure-sdk-tools
        - checkout: azure-sdk-for-net
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK'
          retryCountOnTaskFailure: 3
          inputs:
            useGlobalJson: true
            performMultiLevelLookup: true
        - task: NodeTool@0
          displayName: "Install Node 18.13.0"
          inputs:
            versionSpec: '18.13.0'
        - script: |
            npm ci
          displayName: "Install packages"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - pwsh: ./eng/RegenUsingLocalGenerator.ps1 -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
          failOnStderr: false
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
          displayName: 'Update generator version in Azure SDK repo'
        - template: /eng/common/pipelines/templates/steps/create-pull-request.yml@azure-sdk-tools
          parameters:
            BaseBranchName: main
            RepoName: azure-sdk-for-net
            PRBranchName: AutoGen-$(Build.SourceBranchName)
            CommitMsg: Update AutoRest version according to $(Build.SourceBranchName)
            PRBody: Update AutoRest version according to $(Build.SourceBranchName)
            PRTitle:  Update AutoRest version according to $(Build.SourceBranchName)
            PushArgs: -f
            WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
            ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts