trigger: none

variables:
  NugetSecurityAnalysisWarningLevel: 'none'

resources:
  repositories:
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20220404.3

stages:
  - stage: 'Build_and_Publish'
    jobs:
    - job: Build_and_Publish
      timeoutInMinutes: 120
      pool:
        name: azsdk-pool-mms-win-2022-general
        vmImage: windows-2022
      steps:
        - checkout: self
        - checkout: azure-sdk-tools
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK'
          retryCountOnTaskFailure: 3
          inputs:
            useGlobalJson: true
            performMultiLevelLookup: true
        - task: NodeTool@0
          displayName: "Install Node 18.13.0"
          inputs:
            versionSpec: '18.13.0'
        - script: |
            npm ci
          displayName: "Install packages"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - pwsh: ./eng/PackArtifacts.ps1 -BuildNumber $(Build.BuildNumber) -StagingDirectory $(Build.ArtifactStagingDirectory)
          name: Package
          displayName: "Pack Artifacts"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - task: NuGetCommand@2
          displayName: 'Publish NugetPackage'
          inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: '29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f'
        - task: Npm@1
          displayName: 'Publish @autorest/csharp'
          inputs:
            command: 'publish'
            workingDir: '$(Build.SourcesDirectory)/autorest.csharp/artifacts/bin/AutoRest.CSharp/Release/net6.0'
            publishRegistry: 'useFeed'
            publishFeed: '29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f'
        - pwsh: ./eng/PackEmitter.ps1 -AutorestVersion $(Package.autorestVersion) -StagingDirectory $(Build.ArtifactStagingDirectory)
          displayName: "Pack Emitter"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - task: Npm@1
          displayName: 'Publish @azure-tools/cadl-csharp'
          inputs:
            command: 'publish'
            workingDir: '$(Build.SourcesDirectory)/autorest.csharp/src/CADL.Extension/Emitter.Csharp'
            publishRegistry: 'useFeed'
            publishFeed: '29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f'
        - task: PublishBuildArtifacts@1
          condition: succeededOrFailed()
          displayName: 'Publish Artifacts'
          inputs:
            ArtifactName: packages
  - stage: 'Update_azure_sdk_for_net'
    dependsOn:
      - Build_and_Publish
    variables:
      AutorestCSharpVersion: $[stageDependencies.Build_and_Publish.Build_and_Publish.outputs['Package.autorestVersion']]
      CadlEmitterVersion: $[stageDependencies.Build_and_Publish.Build_and_Publish.outputs['Package.autorestVersion']]
    jobs:
      - template: update-generator-versions.yml
        parameters:
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_A_C
          filter: "a*,b*,c*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_D_E
          filter: "d*,e*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_F_L
          filter: "f*,g*,h*,i*,j*,k*,l*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_M_O
          filter: "m*,n*,o*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_P_R
          filter: "p*,q*,r*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_S_U
          filter: "s*,t*,u*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - template: update-azure-sdk-for-net-codes.yml
        parameters:
          name: Update_Codes_V_Z
          filter: "v*,w*,x*,y*,z*"
          AutorestCSharpVersion: $(AutorestCSharpVersion)
          CadlEmitterVersion: $(CadlEmitterVersion)
          IsInternalFeed: true
      - job: Create_PR
        dependsOn: 
          - Update_Generator_Versions
          - Update_Codes_D_E
          - Update_Codes_F_L
          - Update_Codes_P_R
          - Update_Codes_S_U
          - Update_Codes_V_Z
        steps:
          - checkout: self
          - checkout: azure-sdk-tools
          - task: PowerShell@2
            displayName: Create pull request
            inputs:
              pwsh: true
              filePath: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts/Submit-PullRequest.ps1
              arguments: >
                -RepoOwner "Azure"
                -RepoName "azure-sdk-for-net"
                -BaseBranch "main"
                -PROwner "azure-sdk"
                -PRBranch "auto-update-autorest-$(AutorestCSharpVersion)"
                -AuthToken "$(azuresdk-github-pat)"
                -PRTitle "Autorest Regen Preview to $(AutorestCSharpVersion)"
                -PRBody "Triggered from $(Build.SourceBranch)"
                -OpenAsDraft true
                -PRLabels "Do Not Merge"
