trigger: none

resources:
  repositories:
    - repository: azure-sdk-for-net
      type: github
      name: Azure/azure-sdk-for-net
      endpoint: azure
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure
      ref: refs/tags/azure-sdk-tools_20220404.3

stages:
  - stage: 'Build_and_Publish'
    jobs:
    - job: Build_and_Publish
      timeoutInMinutes: 120
      pool:
        name: azsdk-pool-mms-win-2022-general
        vmImage: windows-2022
      steps:
        - checkout: self
        - task: UseDotNet@2
          displayName: 'Use .NET Core SDK'
          retryCountOnTaskFailure: 3
          inputs:
            useGlobalJson: true
            performMultiLevelLookup: true
        - task: NodeTool@0
          displayName: "Install Node 18.13.0"
          inputs:
            versionSpec: '18.13.0'
        - script: |
            npm ci
          displayName: "Install packages"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - pwsh: ./eng/PackArtifacts.ps1
          displayName: "Pack packages"
          workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
        - task: PublishBuildArtifacts@1
          condition: succeededOrFailed()
          displayName: 'Publish Artifacts'
          inputs:
            ArtifactName: packages