parameters:
  name: ''
  filter: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ubuntu-20.04
  steps:
    - task: NodeTool@0
      displayName: "Install Node 14.x"
      inputs:
        versionSpec: '14.x'
    - script: |
        npm ci
      displayName: "Install packages"
    - pwsh: .\eng\Generate.ps1 -Filter "${{ parameters.filter }}" -Exclude TestServer,TestProjects,Samples -reset
      displayName: "Check if code is up-to-date"
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_MULTILEVEL_LOOKUP: 0
