# Generate SDK codes

parameters:
  name: ''
  filter: ''
  AutorestCSharpVersion: ''
  CadlEmitterVersion: ''
  IsInternalFeed: false

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  pool:
    name: azsdk-pool-mms-ubuntu-2004-general
    vmImage: ubuntu-20.04
  dependsOn: Update_Generator_Versions
  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-for-net
  - checkout: azure-sdk-tools
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      useGlobalJson: true
      performMultiLevelLookup: true
  - ${{ if eq(parameters.IsInternalFeed, true) }}:
    - pwsh: ./eng/GenerateInternalNpmrc.ps1 -ContainingFolder $(Build.SourcesDirectory)/azure-sdk-for-net
      displayName: "Generate Internal Npmrc"
      workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
    - task: npmAuthenticate@0
      inputs:
        workingFile: '.npmrc'
      displayName: Setup Internal NPM Auth
  - task: Powershell@2
    displayName: Update SDK codes ${{ parameters.filter }}
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/autorest.csharp/eng/UpdateAzureSdkForNet.ps1
      arguments: >
        -AutorestCSharpVersion ${{ parameters.AutorestCSharpVersion }}
        -CadlEmitterVersion ${{ parameters.CadlEmitterVersion }}
        -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
        -ServiceDirectoryFilters ${{ parameters.filter}}
        -ShowSummary
        -UseInternalFeed $${{parameters.IsInternalFeed}}
      failOnStderr: false
      workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
    retryCountOnTaskFailure: 3
  - pwsh: |
      git restore eng/Packages.Data.props
      git restore eng/emitter-package.json
    displayName: Discard versions change
    workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
  - ${{ if eq(parameters.IsInternalFeed, true) }}:
    - pwsh: |
        git restore NuGet.Config
        git restore .npmrc
        git restore eng\common\scripts\Cadl-Project-Generate.ps1
      displayName: Discard Internal Change
      workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
    parameters:
      BaseRepoBranch: auto-update-autorest-${{ parameters.AutorestCSharpVersion }}
      BaseRepoOwner: pshao25
      CommitMsg: Update SDK codes ${{ parameters.filter }}
      TargetRepoOwner: Azure
      TargetRepoName: azure-sdk-for-net
      WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
