# Generate SDK codes

parameters:
  Name: ''
  AutorestCSharpVersion: ''
  CadlEmitterVersion: ''
  IsInternalFeed: false
  Matrix: {}
  DependsOn: []

jobs:
- job: ${{ parameters.Name }}
  timeoutInMinutes: 60
  pool:
    name: azsdk-pool-mms-ubuntu-2004-general
    vmImage: ubuntu-20.04
  strategy:
    matrix: ${{ parameters.Matrix }}
  dependsOn: ${{ parameters.DependsOn }}
  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-tools
    fetchDepth: 1
  - template: eng/common/pipelines/templates/steps/sparse-checkout.yml@azure-sdk-tools
    parameters:
      Paths:
      - "/*"
      - "!SessionRecords"
      Repositories:
      - Name: Azure/azure-sdk-for-net
        WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      SkipCheckoutNone: true
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      useGlobalJson: true
      performMultiLevelLookup: true
  - task: DownloadPipelineArtifact@2
    displayName: Download job matrix props files
    inputs:
      artifact: matrix-props
      targetPath: $(Build.SourcesDirectory)/azure-sdk-for-net/matrix-props

  - ${{ if eq(parameters.IsInternalFeed, true) }}:
    - pwsh: ./eng/GenerateInternalNpmrc.ps1 -ContainingFolder $(Build.SourcesDirectory)/azure-sdk-for-net
      displayName: "Generate Internal Npmrc"
      workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
    - task: npmAuthenticate@0
      inputs:
        workingFile: '$(Build.SourcesDirectory)/azure-sdk-for-net/.npmrc'
      displayName: Setup Internal NPM Auth
  - task: Powershell@2
    displayName: Update SDK codes
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/autorest.csharp/eng/UpdateAzureSdkForNet.ps1
      arguments: >
        -AutorestCSharpVersion ${{ parameters.AutorestCSharpVersion }}
        -CadlEmitterVersion ${{ parameters.CadlEmitterVersion }}
        -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
        -ProjectListOverrideFile matrix-props/$(ProjectListOverrideFile)
        -ShowSummary
        -UseInternalFeed $${{parameters.IsInternalFeed}}
      failOnStderr: false
      workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
    retryCountOnTaskFailure: 3
  - pwsh: |
      git restore eng/Packages.Data.props
      git restore eng/emitter-package.json
    displayName: Discard versions change
    workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
  - ${{ if eq(parameters.IsInternalFeed, true) }}:
    - pwsh: |
        git restore NuGet.Config
        git restore eng/common/scripts/TypeSpec-Project-Generate.ps1
        rm .npmrc
      displayName: Discard Internal Change
      workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
    parameters:
      BaseRepoBranch: auto-update-autorest-${{ parameters.AutorestCSharpVersion }}
      BaseRepoOwner: azure-sdk
      CommitMsg: Update SDK codes ${{ parameters.filter }}
      TargetRepoOwner: Azure
      TargetRepoName: azure-sdk-for-net
      WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
