# Generate SDK samples

parameters:
  name: ''
  filter: ''

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 60
  pool:
    name: azsdk-pool-mms-ubuntu-2004-general
    vmImage: ubuntu-20.04
  variables:
    AutorestCSharpVersion: $[stageDependencies.Build_and_Test.Build.outputs['Package.AutorestCSharpVersion']]
    TypeSpecEmitterVersion: $[stageDependencies.Build_and_Test.Build.outputs['Publish.TypeSpecEmitterVersion']]
  dependsOn: Update_Generator_Versions
  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-for-net
  - checkout: azure-sdk-tools
    fetchDepth: 1
  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK'
    inputs:
      useGlobalJson: true
      performMultiLevelLookup: true
  - task: Powershell@2
    displayName: Update SDK samples ${{ parameters.filter }}
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/autorest.csharp/eng/UpdateAzureSdkForNetSamples.ps1
      arguments: >
        -AutorestCSharpVersion $(AutorestCSharpVersion)
        -TypeSpecEmitterVersion $(TypeSpecEmitterVersion)
        -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
        -ServiceDirectoryFilters ${{ parameters.filter}}
        -ShowSummary
      failOnStderr: false
      workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
    retryCountOnTaskFailure: 3
  - pwsh: |
      git restore eng/Packages.Data.props
      git restore eng/emitter-package.json
    displayName: Discard versions change
    workingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
    parameters:
      BaseRepoBranch: auto-update-autorest-$(AutorestCSharpVersion)
      BaseRepoOwner: azure-sdk
      CommitMsg: Update SDK samples ${{ parameters.filter }}
      TargetRepoOwner: Azure
      TargetRepoName: azure-sdk-for-net
      WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
