# Update `autorest.csharp` and cadl emitter versions

jobs:
- job: Update_Generator_Versions
  pool:
    name: azsdk-pool-mms-ubuntu-2004-general
    vmImage: ubuntu-20.04
  variables:
    AutorestCSharpVersion: $[stageDependencies.Build_and_Test.Build.outputs['Package.AutorestCSharpVersion']]
    CadlEmitterVersion: $[stageDependencies.Build_and_Test.Build.outputs['Publish.CadlEmitterVersion']]
  steps:
  - checkout: self
    fetchDepth: 1
  - checkout: azure-sdk-for-net
  - checkout: azure-sdk-tools
    fetchDepth: 1
  - task: Powershell@2
    displayName: Update SDK Generator Versions
    inputs:
      pwsh: true
      filePath: $(Build.SourcesDirectory)/autorest.csharp/eng/UpdateGeneratorMetadata.ps1
      arguments: >
        -AutorestCSharpVersion $(AutorestCSharpVersion)
        -CadlEmitterVersion $(CadlEmitterVersion)
        -SdkRepoRoot $(Build.SourcesDirectory)/azure-sdk-for-net
      workingDirectory: $(Build.SourcesDirectory)/autorest.csharp
  - template: /eng/common/pipelines/templates/steps/git-push-changes.yml@azure-sdk-tools
    parameters:
      BaseRepoBranch: auto-update-autorest-$(AutorestCSharpVersion)
      BaseRepoOwner: azure-sdk
      CommitMsg: Update Generator Version $(AutorestCSharpVersion)
      TargetRepoOwner: Azure
      TargetRepoName: azure-sdk-for-net
      WorkingDirectory: $(Build.SourcesDirectory)/azure-sdk-for-net
      ScriptDirectory: $(Build.SourcesDirectory)/azure-sdk-tools/eng/common/scripts
