// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

export enum InputTypeKind {
    AzureLocation = "AzureLocation",
    Boolean = "Boolean",
    BinaryData = "BinaryData",
    Bytes = "Bytes",
    BytesBase64Url = "BytesBase64Url",
    ContentType = "ContentType",
    Date = "Date",
    DateTime = "DateTime",
    DateTimeISO8601 = "DateTimeISO8601",
    DateTimeRFC1123 = "DateTimeRFC1123",
    DateTimeUnix = "DateTimeUnix",
    DurationISO8601 = "DurationISO8601",
    DurationConstant = "DurationConstant",
    ETag = "Etag",
    Float32 = "Float32",
    Float64 = "Float64",
    Float128 = "Float128",
    Guid = "Guid",
    Int32 = "Int32",
    Int64 = "Int64",
    IPAddress = "IPAddress",
    Object = "Object",
    RequestMethod = "RequestMethod",
    ResourceIdentifier = "ResourceIdentifier",
    ResourceType = "ResourceType",
    Stream = "Stream",
    String = "String",
    Time = "Time",
    Uri = "Uri",
    Enum = "Enum",
    UnKnownKind = "UnknownKind"
}
