// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zapappi.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SipTrunkModel
    {
        /// <summary>
        /// Initializes a new instance of the SipTrunkModel class.
        /// </summary>
        public SipTrunkModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SipTrunkModel class.
        /// </summary>
        public SipTrunkModel(int? id = default(int?), string description = default(string), int? customerId = default(int?), string subscriptionId = default(string), string serverAddress = default(string), string endpointId = default(string), string authUser = default(string), string authPassword = default(string), string notifcationsEmails = default(string), int? globalChannelCap = default(int?), int? inboundChannelCap = default(int?), int? outboundChannelCap = default(int?), bool? useWhitelist = default(bool?), bool? useBlacklist = default(bool?), string forceClid = default(string), string accountCode = default(string), bool? enabled = default(bool?), bool? callRecord = default(bool?), string billingId = default(string))
        {
            Id = id;
            Description = description;
            CustomerId = customerId;
            SubscriptionId = subscriptionId;
            ServerAddress = serverAddress;
            EndpointId = endpointId;
            AuthUser = authUser;
            AuthPassword = authPassword;
            NotifcationsEmails = notifcationsEmails;
            GlobalChannelCap = globalChannelCap;
            InboundChannelCap = inboundChannelCap;
            OutboundChannelCap = outboundChannelCap;
            UseWhitelist = useWhitelist;
            UseBlacklist = useBlacklist;
            ForceClid = forceClid;
            AccountCode = accountCode;
            Enabled = enabled;
            CallRecord = callRecord;
            BillingId = billingId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomerId")]
        public int? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubscriptionId")]
        public string SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ServerAddress")]
        public string ServerAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndpointId")]
        public string EndpointId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AuthUser")]
        public string AuthUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AuthPassword")]
        public string AuthPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NotifcationsEmails")]
        public string NotifcationsEmails { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalChannelCap")]
        public int? GlobalChannelCap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InboundChannelCap")]
        public int? InboundChannelCap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutboundChannelCap")]
        public int? OutboundChannelCap { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UseWhitelist")]
        public bool? UseWhitelist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UseBlacklist")]
        public bool? UseBlacklist { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ForceClid")]
        public string ForceClid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AccountCode")]
        public string AccountCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CallRecord")]
        public bool? CallRecord { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BillingId")]
        public string BillingId { get; set; }

    }
}
