name: GitHub Copilot Setup

# This file contains actions that are used to prepare the environment when GitHub Copilot
# is interacting with this repository. It preinstalls the required tools.

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      contents: read

    steps:
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Install NPM 10.x
        run: npm install -g npm@10.x
          
      - name: Verify installations
        run: |
          echo "Node.js version:"
          node -v
          echo "NPM version:"
          npm -v
          echo ".NET SDK version:"
          dotnet --version
