# This is a basic workflow to help you get started with Actions

name: Fork Sync

on:
  schedule:
    - cron: '*/60 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          token: ${{ secrets.FORK_SYNC_TOKEN }}
          owner: llvm
          base: feature/v3
          head: feature/v3
